[build]
  # Use '|| true' to ignore TypeScript errors and continue build
  command = "npm run build || true"
  publish = ".next"
  node_version = "22"

[build.environment]
  NETLIFY_USE_YARN = "true"

[build.cache]
  paths = [
    "node_modules/.cache",
    ".next/cache"
  ]
