[build]
  command = "npm run build"
  publish = ".next"
  node_version = "22"

[build.environment]
  NETLIFY_USE_YARN = "true"

[build.cache]
  paths = [
    "node_modules/.cache",
    ".next/cache"
  ]
